name: "Setup Foundry"
description: "Install Foundry toolchain (forge, cast, anvil, chisel)"

inputs:
  version:
    description: "Foundry toolchain version"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1.7.0
      with:
        version: ${{ inputs.version }}

    - name: Show Forge version
      shell: bash
      run: forge --version
