name: "Setup Foundry"
description: "Install Foundry toolchain (forge, cast, anvil, chisel)"

inputs:
  version:
    description: "Foundry toolchain version"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@b00af27efadbc7b4ca8b82abbd903b17cc874d2a # v1.9.0
      with:
        version: ${{ inputs.version }}

    - name: Show Forge version
      shell: bash
      run: forge --version
