// Bundle @actions/workflow-parser into dist/workflow-parser.cjs.
//
// The package is published as ESM that imports JSON schemas without import attributes, so
// plain Node cannot load it, and a composite action cannot `npm ci` without network access
// and a Node toolchain on every run. Bundling once with esbuild (CommonJS output so the
// `yaml` dependency's require() calls keep working) gives a single committed file that runs
// on any GitHub-hosted runner. Output is deterministic for a given lockfile, so CI rebuilds it
// with --check and fails when the committed bundle drifts from package-lock.json.
//
//   npm ci --ignore-scripts && npm run build     # after bumping the dependency
//   node build.mjs --check                        # CI: fail on drift
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outfile = join(here, "dist", "workflow-parser.cjs");
const check = process.argv.includes("--check");

// Neither package exports its package.json, so read them from node_modules directly.
const version = (pkg) => JSON.parse(readFileSync(join(here, "node_modules", pkg, "package.json"), "utf8")).version;
const parserVersion = version("@actions/workflow-parser");
const esbuildVersion = version("esbuild");

const banner = [
  `// @actions/workflow-parser ${parserVersion}, bundled by esbuild ${esbuildVersion}.`,
  "// Generated by build.mjs; do not edit. Rebuild with `npm ci --ignore-scripts && npm run build`.",
  "// License: MIT (see node_modules/@actions/workflow-parser/LICENSE at that version).",
].join("\n");

const result = await build({
  entryPoints: [join(here, "bundle-entry.mjs")],
  bundle: true,
  format: "cjs",
  platform: "node",
  target: "node20",
  legalComments: "none",
  banner: { js: banner },
  write: false,
  logLevel: "warning",
});
const text = result.outputFiles[0].text;

if (check) {
  let current = "";
  try {
    current = readFileSync(outfile, "utf8");
  } catch {
    // missing file is drift too
  }
  if (current !== text) {
    console.error(
      `::error::ensure-secure-runner: ${outfile} does not match package-lock.json; ` +
        "run `npm ci --ignore-scripts && npm run build` in actions/ensure-secure-runner and commit dist/",
    );
    process.exit(1);
  }
  console.log(`ok: dist/workflow-parser.cjs matches @actions/workflow-parser ${parserVersion}`);
} else {
  writeFileSync(outfile, text);
  console.log(`wrote ${outfile} (${(text.length / 1024).toFixed(0)} KiB) from @actions/workflow-parser ${parserVersion}`);
}
