name: dependencies

on:
  workflow_call:
    inputs:
      rust-toolchain:
        description: "Rust toolchain; same syntax as dtolnay/rust-toolchain"
        default: "nightly"
        required: false
        type: "string"
      title:
        description: "PR title"
        default: "chore(deps): weekly `cargo update`"
        required: false
        type: "string"
    secrets:
      token:
        description: "GITHUB_TOKEN. See https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#token"
        required: true

permissions: {}

env:
  GITHUB_TOKEN: ${{ secrets.token }}
  BRANCH: cargo-update
  BODY: |
    Automation to keep dependencies in `Cargo.lock` current.

    <details><summary><strong>cargo update log</strong></summary>
    <p>

    ```log
    $cargo_update_log
    ```

    </p>
    </details>

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-toolchain }}

      - name: cargo update
        # Remove first line that always just says "Updating crates.io index"
        run: cargo update --color never --verbose 2>&1 | sed '/crates.io index/d' | tee -a cargo_update.log

      - name: Craft commit message and PR body
        id: msg
        env:
          PR_TITLE: ${{ inputs.title }}
        run: |
          export cargo_update_log="$(cat cargo_update.log)"

          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          printf "%s\n\n%s\n" "$PR_TITLE" "$cargo_update_log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" | envsubst >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: ./Cargo.lock
          commit-message: ${{ steps.msg.outputs.commit_message }}
          title: ${{ inputs.title }}
          body: ${{ steps.msg.outputs.body }}
          branch: ${{ env.BRANCH }}
