name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  workflow-validation:
    name: Workflow validation
    uses: ./.github/workflows/workflow-validation.yml
    permissions:
      actions: read
      contents: read
