name: Dependency Scan

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  scan:
    name: Dependency Scan (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@9714ff353c4199ff9f498205ef7b3319869dd51d # 2026-09-25T18-10-33Z-9714ff35
    with:
      runs-on: ${{ matrix.os }}
      artifact-name: dependency-scan-${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
