name: Dependency Scan

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  scan:
    name: Dependency Scan (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@d0bd3f715fb4efadb78897db98fe87e7c94a6d95 # 2026-09-25T07-58-59Z-d0bd3f71
    with:
      runs-on: ${{ matrix.os }}
      artifact-name: dependency-scan-${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
