name: Label PRs

on:
  workflow_call:

permissions:
  id-token: write

jobs:
  label-prs:
    name: Label PRs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@392079a54ac0240e1b21417eca38b7c0a50bf55d # 2026-10-01T18-10-09Z-392079a5

      - name: Checkout shared actions
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # main
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .gh-actions
          persist-credentials: false

      - name: Label PRs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const label_pr = require('./.gh-actions/.github/scripts/label_pr.js')
            await label_pr({github, context})
