# Tagging each commit ensures when we reference commits in other repos that
# we can always include a tag which prevents referencing phantom commits from
# fork PRs.

name: Tag Release

on:
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  tag:
    name: Tag release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@cfdaf2e39309260bff640fb06cf1ab2f9f57386b # 2026-09-25T04-44-11Z-cfdaf2e3

      - name: Checkout pushed revision
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ github.sha }}

      - name: Create timestamp tag
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          REVISION: ${{ github.sha }}
        run: |
          set -euo pipefail
          tag="$(date -u +'%Y-%m-%dT%H-%M-%SZ')-${REVISION:0:8}"
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git tag --annotate "$tag" "$REVISION" --message "Main branch at $tag"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPOSITORY}.git" "refs/tags/$tag"
